# Generated by Django 5.0.1 on 2024-01-25 12:20

import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("auto_id", models.PositiveIntegerField(db_index=True, unique=True)),
                ("a_id", models.PositiveIntegerField()),
                ("date_added", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("date_updated", models.DateTimeField(auto_now_add=True)),
                (
                    "firstname",
                    models.CharField(
                        max_length=125, verbose_name="Contact Person Firstname"
                    ),
                ),
                (
                    "lastname",
                    models.CharField(
                        max_length=125, verbose_name="Contact Person Lastname"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Phone Number"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Address"),
                ),
                (
                    "company_name",
                    models.CharField(
                        max_length=255, verbose_name="Client Company Name"
                    ),
                ),
                (
                    "clientid",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Client ID"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="button to toggle employee deleted and undelete",
                        verbose_name="Is This Employee Deleted ?",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "ordering": ["company_name"],
            },
        ),
    ]
