# Generated by Django 5.0.1 on 2024-03-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0004_alter_client_is_deleted_alter_client_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="clientid",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Client ID",
            ),
        ),
    ]
