# Generated by Django 5.0.1 on 2024-03-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0005_alter_client_clientid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(max_length=255, verbose_name="Phone Number"),
        ),
    ]
