# Generated by Django 5.0.1 on 2024-05-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0006_alter_client_phone"),
        ("main", "0005_portfolio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="clientid",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Client ID"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="client",
            unique_together={("company", "clientid")},
        ),
    ]
