# Generated by Django 5.0.1 on 2024-05-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0007_alter_client_clientid_alter_client_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="company_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Client Company Name",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, unique=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="firstname",
            field=models.CharField(
                max_length=255, verbose_name="Contact Person Firstname"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="lastname",
            field=models.CharField(
                blank=True,
                max_length=125,
                null=True,
                verbose_name="Contact Person Lastname",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Phone Number"
            ),
        ),
    ]
