# Generated by Django 5.0.1 on 2024-04-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hrmsclient",
            name="is_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
