# Generated by Django 5.0.1 on 2024-01-10 10:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hrms", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hrmsclient",
            name="employee_profile_url",
        ),
        migrations.RemoveField(
            model_name="hrmsclient",
            name="leave_application_url",
        ),
        migrations.RemoveField(
            model_name="hrmsclient",
            name="payroll_salary_url",
        ),
    ]
