# Generated by Django 5.0.1 on 2024-05-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrms", "0002_hrmsclient_is_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="hrmsclient",
            name="is_attendance_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
