# Generated by Django 5.0.1 on 2024-05-16 09:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hrms", "0003_hrmsclient_is_attendance_enabled"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hrmsclient",
            options={
                "ordering": ["first_name"],
                "verbose_name": "Hrms Client",
                "verbose_name_plural": "Hrms Clients",
            },
        ),
    ]
