# Generated by Django 5.0.1 on 2024-06-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendanceregister",
            name="status",
            field=models.CharField(
                choices=[
                    ("half-day", "Half"),
                    ("absent", "Absent"),
                    ("present", "Present"),
                ],
                default="absent",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=125,
                null=True,
                verbose_name="Gender",
            ),
        ),
    ]
