# Generated by Django 5.0.1 on 2024-06-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0003_alter_attendanceregister_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendanceregister",
            name="status",
            field=models.CharField(
                choices=[
                    ("absent", "Absent"),
                    ("present", "Present"),
                    ("half-day", "Half"),
                ],
                default="absent",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Other", "Other"), ("Female", "Female"), ("Male", "Male")],
                max_length=125,
                null=True,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="leave",
            name="reason",
            field=models.CharField(
                default="casual",
                help_text="add additional information for leave",
                max_length=255,
                verbose_name="Leave Reason",
            ),
            preserve_default=False,
        ),
    ]
