# Generated by Django 5.0.1 on 2024-01-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0004_leavetype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leavetype",
            name="days",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Number of Days"
            ),
        ),
    ]
