# Generated by Django 5.0.1 on 2024-06-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0004_alter_attendanceregister_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendanceregister",
            name="status",
            field=models.CharField(
                choices=[
                    ("half-day", "Half"),
                    ("present", "Present"),
                    ("absent", "Absent"),
                ],
                default="absent",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Female", "Female"), ("Other", "Other"), ("Male", "Male")],
                max_length=125,
                null=True,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="leavetype",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
