# Generated by Django 5.0.1 on 2024-07-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0006_alter_employee_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=125, verbose_name="Name")),
                (
                    "date",
                    models.DateField(
                        help_text="due_date", null=True, verbose_name="Date"
                    ),
                ),
                ("is_hide", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "admin holiday",
                "verbose_name_plural": "admin holidays",
                "db_table": "admin_holiday",
            },
        ),
        migrations.AlterField(
            model_name="attendanceregister",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "Present"),
                    ("absent", "Absent"),
                    ("half-day", "Half"),
                ],
                default="absent",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Female", "Female"), ("Other", "Other"), ("Male", "Male")],
                max_length=125,
                null=True,
                verbose_name="Gender",
            ),
        ),
    ]
