# Generated by Django 5.0.1 on 2024-07-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_employee_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceregister',
            name='status',
            field=models.CharField(choices=[('half-day', 'Half'), ('absent', 'Absent'), ('present', 'Present')], default='absent', max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('Other', 'Other'), ('Female', 'Female'), ('Male', 'Male')], max_length=125, null=True, verbose_name='Gender'),
        ),
    ]
