# Generated by Django 4.2.1 on 2024-07-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0007_adminholiday_alter_attendanceregister_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendanceregister",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "Present"),
                    ("half-day", "Half"),
                    ("absent", "Absent"),
                ],
                default="absent",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Other", "Other"), ("Female", "Female"), ("Male", "Male")],
                max_length=125,
                null=True,
                verbose_name="Gender",
            ),
        ),
    ]
