# Generated by Django 5.0.1 on 2024-07-12 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_adminholiday_alter_attendanceregister_status_and_more'),
        ('employee', '0007_alter_attendanceregister_status_and_more'),
    ]

    operations = [
    ]
