# Generated by Django 5.0.1 on 2024-07-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_merge_20240712_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceregister',
            name='status',
            field=models.CharField(choices=[('absent', 'Absent'), ('half-day', 'Half'), ('present', 'Present')], default='absent', max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], max_length=125, null=True, verbose_name='Gender'),
        ),
    ]
