# Generated by Django 5.0.1 on 2024-02-19 08:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0008_alter_leave_status_attendenceregister"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AttendenceRegister",
        ),
    ]
