<<<<<<< HEAD
# Generated by Django 4.2.1 on 2024-07-23 05:16
=======
# Generated by Django 5.0.1 on 2024-07-23 12:34
>>>>>>> 0ed7fa85046daba4a689190bb98416557fb074e9

from django.db import migrations, models


class Migration(migrations.Migration):
<<<<<<< HEAD
    dependencies = [
        ("employee", "0008_alter_attendanceregister_status_and_more"),
=======

    dependencies = [
        ('employee', '0008_merge_20240712_0622'),
>>>>>>> 0ed7fa85046daba4a689190bb98416557fb074e9
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name="attendanceregister",
            name="status",
            field=models.CharField(
                choices=[
                    ("absent", "Absent"),
                    ("present", "Present"),
                    ("half-day", "Half"),
                ],
                default="absent",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Other", "Other"), ("Female", "Female")],
                max_length=125,
                null=True,
                verbose_name="Gender",
            ),
=======
            model_name='attendanceregister',
            name='status',
            field=models.CharField(choices=[('absent', 'Absent'), ('half-day', 'Half'), ('present', 'Present')], default='absent', max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], max_length=125, null=True, verbose_name='Gender'),
>>>>>>> 0ed7fa85046daba4a689190bb98416557fb074e9
        ),
    ]
