# Generated by Django 5.0.1 on 2024-02-19 08:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0009_delete_attendenceregister"),
        ("main", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceRegister",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("auto_id", models.PositiveIntegerField(db_index=True, unique=True)),
                ("a_id", models.PositiveIntegerField()),
                ("date_added", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("date_updated", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("absent", "Absent"),
                            ("present", "Present"),
                            ("half-day", "Half"),
                        ],
                        default="absent",
                        max_length=15,
                    ),
                ),
                ("date", models.DateField()),
                ("is_attended", models.BooleanField(default=True)),
                ("is_fn", models.BooleanField(default=True)),
                ("is_an", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        limit_choices_to={"is_deleted": False},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.company",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator_%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        limit_choices_to={"is_deleted": False},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee.employee",
                    ),
                ),
                (
                    "updator",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updator_%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "attendence register",
                "verbose_name_plural": "attendence registers",
                "db_table": "attendence_register",
            },
        ),
    ]
