# Generated by Django 5.0.1 on 2024-03-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0042_alter_attendanceregister_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="is_rejected",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="attendanceregister",
            name="status",
            field=models.CharField(
                choices=[
                    ("half-day", "Half"),
                    ("present", "Present"),
                    ("absent", "Absent"),
                ],
                default="absent",
                max_length=15,
            ),
        ),
    ]
