# Generated by Django 5.0.1 on 2024-03-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0051_alter_attendanceregister_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendanceregister",
            name="status",
            field=models.CharField(
                choices=[
                    ("absent", "Absent"),
                    ("half-day", "Half"),
                    ("present", "Present"),
                ],
                default="absent",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="joindate",
            field=models.DateField(
                blank=True,
                help_text="joining date",
                null=True,
                verbose_name="Joining Date",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=models.CharField(max_length=255, verbose_name="Phone Number"),
        ),
    ]
