# Generated by Django 5.0.1 on 2024-05-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0065_alter_attendanceregister_status"),
        ("main", "0005_portfolio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendanceregister",
            name="status",
            field=models.CharField(
                choices=[
                    ("absent", "Absent"),
                    ("half-day", "Half"),
                    ("present", "Present"),
                ],
                default="absent",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="employeeid",
            field=models.CharField(
                blank=True, max_length=125, null=True, verbose_name="Employee ID"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="employee",
            unique_together={("company", "employeeid")},
        ),
    ]
