# Generated by Django 5.0.1 on 2024-05-06 04:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0067_alter_attendanceregister_status"),
        ("main", "0005_portfolio"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendanceregister",
            name="status",
            field=models.CharField(
                choices=[
                    ("absent", "Absent"),
                    ("present", "Present"),
                    ("half-day", "Half"),
                ],
                default="absent",
                max_length=15,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="employee",
            unique_together={("user", "company", "employeeid")},
        ),
    ]
