# Generated by Django 5.0.1 on 2024-05-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0073_alter_attendanceregister_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="client_company",
        ),
        migrations.AlterField(
            model_name="employee",
            name="employeeid",
            field=models.CharField(
                default="Emp-004", max_length=125, verbose_name="Employee ID"
            ),
            preserve_default=False,
        ),
    ]
