# Generated by Django 5.0.1 on 2024-07-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asset", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="salvage_value",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Salvage/Scrap Value"
            ),
        ),
    ]
