# Generated by Django 4.2.1 on 2024-07-31 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("auto_id", models.PositiveIntegerField(db_index=True, unique=True)),
                ("date_added", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("date_updated", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=128, verbose_name="Company Name")),
                (
                    "contact_person",
                    models.CharField(max_length=128, verbose_name="Contact Person"),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Address"),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="City"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Postal Code",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(max_length=128, verbose_name="Phone Number"),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Mobile Number",
                    ),
                ),
                (
                    "fax",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="Fax"
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Website"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="logos/", verbose_name="Photo"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, verbose_name="Is this company deleted ? "
                    ),
                ),
            ],
            options={
                "verbose_name": "company",
                "verbose_name_plural": "companies",
                "db_table": "company",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("iso3", models.CharField(max_length=128)),
                ("iso2", models.CharField(max_length=128)),
                ("numeric_code", models.CharField(max_length=128)),
                ("phone_code", models.CharField(max_length=128)),
                ("capital", models.CharField(max_length=128)),
                ("currency", models.CharField(max_length=128)),
                ("currency_symbol", models.CharField(max_length=128)),
                ("tld", models.CharField(max_length=128)),
                ("native", models.CharField(max_length=128)),
                ("region", models.CharField(max_length=128)),
                ("subregion", models.CharField(max_length=128)),
                ("latitude", models.CharField(max_length=128)),
                ("longitude", models.CharField(max_length=128)),
            ],
            options={
                "verbose_name": "country",
                "verbose_name_plural": "countries",
                "db_table": "countries",
            },
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80, verbose_name="Title")),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Description"),
                ),
                ("image", models.ImageField(upload_to="portfolio_images/")),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "portfolio",
                "verbose_name_plural": "portfolio",
                "db_table": "main_portfolio",
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("country_code", models.CharField(max_length=128)),
                ("state_code", models.CharField(max_length=128)),
                ("latitude", models.CharField(max_length=128)),
                ("longitude", models.CharField(max_length=128)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.country"
                    ),
                ),
            ],
            options={
                "verbose_name": "state",
                "verbose_name_plural": "states",
                "db_table": "states",
            },
        ),
        migrations.CreateModel(
            name="EmailSetting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("auto_id", models.PositiveIntegerField(db_index=True, unique=True)),
                ("a_id", models.PositiveIntegerField()),
                ("date_added", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("date_updated", models.DateTimeField(auto_now_add=True)),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        limit_choices_to={"is_deleted": False},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.company",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator_%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updator",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updator_%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Setting",
                "verbose_name_plural": "Email Settings",
                "ordering": ["email"],
            },
        ),
        migrations.CreateModel(
            name="CompanyAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_accepted", models.BooleanField(default=False)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_deleted": False},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.company",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.group"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "company_access",
                "verbose_name_plural": "company_access",
                "db_table": "company_access",
                "ordering": ("company",),
            },
        ),
        migrations.AddField(
            model_name="company",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.country"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creator_%(class)s_objects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.state"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="updator",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updator_%(class)s_objects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
