# Generated by Django 5.0.1 on 2024-04-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_company_mobile_alter_company_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80, verbose_name="Title")),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Description"),
                ),
                ("image", models.ImageField(upload_to="portfolio_images/")),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "portfolio",
                "verbose_name_plural": "portfolio",
                "db_table": "main_portfolio",
            },
        ),
    ]
