# Generated by Django 4.2.1 on 2024-07-30 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employee", "0001_initial"),
        ("main", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("auto_id", models.PositiveIntegerField(db_index=True, unique=True)),
                ("a_id", models.PositiveIntegerField()),
                ("date_added", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("date_updated", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=125, verbose_name="Project Name")),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="start date",
                        null=True,
                        verbose_name="Start Date",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="end date",
                        null=True,
                        verbose_name="End Date",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Low", "Low"),
                            ("Normal", "Normal"),
                            ("High", "High"),
                        ],
                        default="Normal",
                        max_length=128,
                        null=True,
                    ),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="files/")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description "
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        limit_choices_to={"is_deleted": False},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.company",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator_%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project_leader",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_deleted": False},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_leader",
                        to="employee.employee",
                    ),
                ),
                (
                    "team",
                    models.ManyToManyField(
                        related_name="project_team",
                        to="employee.employee",
                        verbose_name="Team",
                    ),
                ),
                (
                    "updator",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updator_%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TaskBoard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("auto_id", models.PositiveIntegerField(db_index=True, unique=True)),
                ("a_id", models.PositiveIntegerField()),
                ("date_added", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("date_updated", models.DateTimeField(auto_now_add=True)),
                (
                    "name",
                    models.CharField(max_length=125, verbose_name="Task Board Name"),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        limit_choices_to={"is_deleted": False},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.company",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator_%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        limit_choices_to={"is_deleted": False},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taskboard.project",
                    ),
                ),
                (
                    "updator",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updator_%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Board",
                "verbose_name_plural": "Task Boards",
                "ordering": ["name"],
            },
        ),
    ]
