# Generated by Django 4.2.1 on 2024-07-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0008_alter_attendanceregister_status_and_more"),
        ("taskboard", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="project_leader",
        ),
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.DateField(
                blank=True, help_text="end date", null=True, verbose_name="End Date"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="team",
            field=models.ManyToManyField(
                related_name="project_team", to="employee.employee", verbose_name="Team"
            ),
        ),
    ]
