# Generated by Django 4.2.1 on 2024-07-23 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0009_alter_attendanceregister_status_and_more"),
        (
            "taskboard",
            "0002_remove_project_project_leader_alter_project_end_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_leader",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_deleted": False},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_leader",
                to="employee.employee",
            ),
        ),
    ]
