# Generated by Django 4.2.1 on 2024-07-31 01:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Last Name"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="candidates/photos/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=255, verbose_name="Phone Number"),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Address"),
                ),
                (
                    "education",
                    models.TextField(
                        blank=True, null=True, verbose_name="Highest Level Of Education"
                    ),
                ),
                (
                    "experience",
                    models.TextField(
                        blank=True, null=True, verbose_name="Experience in years"
                    ),
                ),
                ("skills", models.TextField(verbose_name="Skills")),
                (
                    "certifications",
                    models.FileField(
                        blank=True, null=True, upload_to="candidates/certificates/"
                    ),
                ),
                (
                    "projects",
                    models.URLField(
                        blank=True,
                        null=True,
                        verbose_name="Portfolio/ Work Samples/ Github Links",
                    ),
                ),
                ("additional_information", models.TextField(blank=True, null=True)),
                (
                    "linkedin_profile",
                    models.URLField(
                        blank=True, null=True, verbose_name="LinkedIn Profile Link"
                    ),
                ),
                (
                    "github_profile",
                    models.URLField(
                        blank=True, null=True, verbose_name=" Github Links"
                    ),
                ),
                (
                    "resume",
                    models.FileField(
                        blank=True, null=True, upload_to="candidates/resumes/"
                    ),
                ),
                ("date_applied", models.DateTimeField(auto_now_add=True)),
                (
                    "candidateid",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Candidate ID",
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Full Time", "Full Time"),
                            ("Part Time", "Part Time"),
                            ("Contract", "Contract"),
                        ],
                        default="Full Time",
                        max_length=255,
                        null=True,
                        verbose_name="Select Job Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("No Offer", "No Offer"),
                            ("Offer a job", "Offer a job"),
                            ("Job Offered", "Job Offered"),
                            ("Assign Task", "Assign Task"),
                            ("Interested in the Job", "Interested in the Job"),
                            ("Interview Scheduled", "Interview Scheduled"),
                            ("Interview Done", "Interview Done"),
                            ("Cancelled/Rejected", "Cancelled/Rejected"),
                        ],
                        default="No Offer",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "is_blocked",
                    models.BooleanField(
                        default=False,
                        help_text="button to toggle candidate block and unblock",
                        verbose_name="Is Blocked",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-date_applied"],
            },
        ),
        migrations.CreateModel(
            name="Intern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(max_length=255, verbose_name="Phone Number"),
                ),
                (
                    "intern_linkedin",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="linkedin Profile Link",
                    ),
                ),
                (
                    "intern_git",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="GitHub Profile Link",
                    ),
                ),
                (
                    "resume",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="resumes/",
                        verbose_name="Upload your resume",
                    ),
                ),
                ("skills", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("Full Stack Development", "Full Stack Development"),
                            ("Marketing", "Marketing"),
                            ("Accounting", "Accounting"),
                            ("Design Engineering", "Design Engineering"),
                            ("Matlab", "Matlab"),
                        ],
                        default="Full Stack Development",
                        max_length=255,
                        verbose_name="Select your domain",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "intern",
                "verbose_name_plural": "interns",
                "db_table": "candidate_intern",
            },
        ),
    ]
