# Generated by Django 5.0.1 on 2024-01-25 12:20

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("auto_id", models.PositiveIntegerField(db_index=True, unique=True)),
                ("a_id", models.PositiveIntegerField()),
                ("date_added", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("date_updated", models.DateTimeField(auto_now_add=True)),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Last Name"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="photos/", verbose_name="Photo"
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Phone Number"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Address"),
                ),
                (
                    "education",
                    models.TextField(
                        blank=True, null=True, verbose_name="Highest Level Of Education"
                    ),
                ),
                (
                    "experience",
                    models.TextField(
                        blank=True, null=True, verbose_name="Experience in years"
                    ),
                ),
                ("skills", models.TextField(verbose_name="Skills")),
                (
                    "certifications",
                    models.FileField(blank=True, null=True, upload_to="certificates/"),
                ),
                (
                    "projects",
                    models.URLField(
                        blank=True,
                        null=True,
                        verbose_name="Portfolio/ Work Samples/ Github Links",
                    ),
                ),
                ("additional_information", models.TextField(blank=True, null=True)),
                (
                    "linkedin_profile",
                    models.URLField(
                        blank=True, null=True, verbose_name="LinkedIn Profile Link"
                    ),
                ),
                (
                    "github_profile",
                    models.URLField(
                        blank=True, null=True, verbose_name=" Github Links"
                    ),
                ),
                (
                    "resume",
                    models.FileField(blank=True, null=True, upload_to="resumes/"),
                ),
                ("date_applied", models.DateTimeField(auto_now_add=True)),
                (
                    "is_blocked",
                    models.BooleanField(
                        default=False,
                        help_text="button to toggle employee block and unblock",
                        verbose_name="Is Blocked",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator_%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updator",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updator_%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_applied"],
            },
        ),
    ]
