# Generated by Django 5.0.1 on 2024-03-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="a_id",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="auto_id",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="date_added",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="date_updated",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="updator",
        ),
        migrations.AlterField(
            model_name="candidate",
            name="certifications",
            field=models.FileField(
                blank=True, null=True, upload_to="candidates/certificates/"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="candidates/photos/",
                verbose_name="Photo",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="resume",
            field=models.FileField(
                blank=True, null=True, upload_to="candidates/resumes/"
            ),
        ),
    ]
