# Generated by Django 5.0.1 on 2024-03-14 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0002_remove_candidate_a_id_remove_candidate_auto_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="user",
        ),
    ]
