# Generated by Django 5.0.1 on 2024-03-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0003_remove_candidate_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="candidateid",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Candidate ID",
            ),
        ),
    ]
