# Generated by Django 5.0.1 on 2024-03-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0004_candidate_candidateid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="phone_number",
            field=models.CharField(max_length=255, verbose_name="Phone Number"),
        ),
    ]
