# Generated by Django 5.0.1 on 2024-04-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0005_alter_candidate_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Intern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(max_length=255, verbose_name="Phone Number"),
                ),
                (
                    "intern_linkedin",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="linkedin Profile Link",
                    ),
                ),
                (
                    "intern_git",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="GitHub Profile Link",
                    ),
                ),
                (
                    "resume",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="resumes/",
                        verbose_name="Upload your resume",
                    ),
                ),
                ("skills", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("Full Stack Development", "Full Stack Development"),
                            ("Marketing", "Marketing"),
                            ("Accounting", "Accounting"),
                            ("Design Engineering", "Design Engineering"),
                            ("Matlab", "Matlab"),
                        ],
                        default="Full Stack Development",
                        max_length=255,
                        verbose_name="Select your domain",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "intern",
                "verbose_name_plural": "interns",
                "db_table": "candidate_intern",
            },
        ),
    ]
