# Generated by Django 5.0.1 on 2024-04-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0006_intern"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("Full Time", "Full Time"),
                    ("Part Time", "Part Time"),
                    ("Contract", "Contract"),
                ],
                default="Full Time",
                max_length=255,
                verbose_name="Select Job Type",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="is_blocked",
            field=models.BooleanField(
                default=False,
                help_text="button to toggle candidate block and unblock",
                verbose_name="Is Blocked",
            ),
        ),
    ]
