# Generated by Django 5.0.1 on 2024-04-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0007_candidate_job_type_alter_candidate_is_blocked"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="status",
            field=models.CharField(
                choices=[
                    ("No Offer", "No Offer"),
                    ("Job Offered", "Job Offered"),
                    ("Assign Task", "Assign Task"),
                    ("Schedule Interview", "Schedule Interview"),
                ],
                default="No Offer",
                max_length=255,
            ),
        ),
    ]
