# Generated by Django 5.0.1 on 2024-04-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0008_candidate_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="job_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Full Time", "Full Time"),
                    ("Part Time", "Part Time"),
                    ("Contract", "Contract"),
                ],
                default="Full Time",
                max_length=255,
                null=True,
                verbose_name="Select Job Type",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Offer a job", "Offer a job"),
                    ("Job Offered", "Job Offered"),
                    ("Assign Task", "Assign Task"),
                    ("Interested in the Job", "Interested in the Job"),
                    ("Interview Scheduled", "Interview Scheduled"),
                    ("Interview Done", "Interview Done"),
                    ("Cancelled/Rejected", "Cancelled/Rejected"),
                ],
                default="No Offer",
                max_length=255,
                null=True,
            ),
        ),
    ]
