# Generated by Django 5.0.1 on 2024-05-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0009_alter_candidate_job_type_alter_candidate_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("No Offer", "No Offer"),
                    ("Offer a job", "Offer a job"),
                    ("Job Offered", "Job Offered"),
                    ("Assign Task", "Assign Task"),
                    ("Interested in the Job", "Interested in the Job"),
                    ("Interview Scheduled", "Interview Scheduled"),
                    ("Interview Done", "Interview Done"),
                    ("Cancelled/Rejected", "Cancelled/Rejected"),
                ],
                default="No Offer",
                max_length=255,
                null=True,
            ),
        ),
    ]
