# Generated by Django 5.0.1 on 2024-02-20 05:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SalarySettings",
        ),
    ]
