# Generated by Django 5.0.1 on 2024-02-20 06:16

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salarysetting",
            name="da",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="DA(%)",
            ),
        ),
        migrations.AlterField(
            model_name="salarysetting",
            name="esi_emp",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Employee Share(%)",
            ),
        ),
        migrations.AlterField(
            model_name="salarysetting",
            name="esi_org",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Employee Share(%)",
            ),
        ),
        migrations.AlterField(
            model_name="salarysetting",
            name="hra",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="HRA(%)",
            ),
        ),
        migrations.AlterField(
            model_name="salarysetting",
            name="is_deleted",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="button to toggle employee deleted and undelete",
                null=True,
                verbose_name="Is This Salary Settings Deleted ?",
            ),
        ),
        migrations.AlterField(
            model_name="salarysetting",
            name="pf_emp",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Employee Share(%)",
            ),
        ),
        migrations.AlterField(
            model_name="salarysetting",
            name="pf_org",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Organization Share(%)",
            ),
        ),
        migrations.AlterField(
            model_name="salarysetting",
            name="tds",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Employee Share(%)",
            ),
        ),
    ]
