# Generated by Django 5.0.1 on 2024-02-20 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0005_alter_salarysetting_esi_emp_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payrollitem",
            options={
                "ordering": ["item"],
                "verbose_name": "Payroll Item",
                "verbose_name_plural": "Payroll Items",
            },
        ),
        migrations.RemoveField(
            model_name="payrollitem",
            name="name",
        ),
        migrations.AddField(
            model_name="payrollitem",
            name="item",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_deleted": False},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payroll.salarysetting",
            ),
        ),
    ]
