# Generated by Django 5.0.1 on 2024-02-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0006_alter_payrollitem_options_remove_payrollitem_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payrollitem",
            options={
                "ordering": ["name"],
                "verbose_name": "Payroll Item",
                "verbose_name_plural": "Payroll Items",
            },
        ),
        migrations.RemoveField(
            model_name="payrollitem",
            name="item",
        ),
        migrations.AddField(
            model_name="payrollitem",
            name="name",
            field=models.CharField(
                default="da", max_length=255, verbose_name="Payroll Item Name"
            ),
            preserve_default=False,
        ),
    ]
