# Generated by Django 5.0.1 on 2024-02-22 11:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0008_salary"),
    ]

    operations = [
        migrations.AddField(
            model_name="salary",
            name="net_salary",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Net Salary",
            ),
        ),
    ]
