# Generated by Django 5.0.1 on 2024-02-24 04:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0009_salary_net_salary"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="salary",
            options={
                "ordering": ["employee"],
                "verbose_name": "Salary",
                "verbose_name_plural": "Salary",
            },
        ),
        migrations.RemoveField(
            model_name="salary",
            name="payroll_item",
        ),
    ]
