# Generated by Django 5.0.1 on 2024-02-24 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0010_alter_salary_options_remove_salary_payroll_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="salary",
            name="payroll_item",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_deleted": False},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payroll.payrollitem",
            ),
        ),
        migrations.AddField(
            model_name="salary",
            name="payroll_item_category",
            field=models.CharField(default="Additions", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="salary",
            name="payroll_item_value",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=15),
            preserve_default=False,
        ),
    ]
