# Generated by Django 5.0.1 on 2024-02-24 15:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0011_salary_payroll_item_salary_payroll_item_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salary",
            name="payroll_item",
        ),
        migrations.RemoveField(
            model_name="salary",
            name="payroll_item_category",
        ),
        migrations.RemoveField(
            model_name="salary",
            name="payroll_item_value",
        ),
    ]
