# Generated by Django 5.0.1 on 2024-02-25 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0023_alter_attendanceregister_status"),
        ("main", "0001_initial"),
        ("payroll", "0013_payslip"),
    ]

    operations = [
        migrations.AddField(
            model_name="payslip",
            name="company",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_deleted": False},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.company",
            ),
        ),
        migrations.AddField(
            model_name="payslip",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_deleted": False},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="employee.employee",
            ),
        ),
    ]
