# Generated by Django 5.0.1 on 2024-02-25 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0014_payslip_company_payslip_employee"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="salary",
            options={
                "ordering": ["employee"],
                "verbose_name": "Salary",
                "verbose_name_plural": "Salaries",
            },
        ),
        migrations.AddField(
            model_name="payslip",
            name="date",
            field=models.DateField(default=datetime.date.today, verbose_name="Date"),
        ),
        migrations.AddField(
            model_name="payslip",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="button to toggle employee deleted and undelete",
                verbose_name="Is This Employee Deleted ?",
            ),
        ),
    ]
