# Generated by Django 5.0.1 on 2024-02-26 04:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0015_alter_salary_options_payslip_date_payslip_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payslip",
            name="payroll_item",
        ),
    ]
