# Generated by Django 5.0.1 on 2024-02-26 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0016_remove_payslip_payroll_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="payslip",
            name="payroll_items",
            field=models.ManyToManyField(to="payroll.payrollitem"),
        ),
    ]
