# Generated by Django 5.0.1 on 2024-02-26 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0017_payslip_payroll_items"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payslip",
            name="category",
        ),
        migrations.RemoveField(
            model_name="payslip",
            name="payroll_items",
        ),
        migrations.RemoveField(
            model_name="payslip",
            name="value",
        ),
        migrations.CreateModel(
            name="PaySlipItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=15)),
                ("category", models.CharField(max_length=128)),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="button to toggle employee deleted and undelete",
                        verbose_name="Is This Employee Deleted ?",
                    ),
                ),
                (
                    "payroll_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payroll.payrollitem",
                    ),
                ),
                (
                    "payslip",
                    models.ForeignKey(
                        limit_choices_to={"is_deleted": False},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payroll.payslip",
                    ),
                ),
            ],
            options={
                "verbose_name": "PaySlip Item",
                "verbose_name_plural": "PaySlip Items",
            },
        ),
    ]
