# Generated by Django 5.0.1 on 2024-02-26 06:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "payroll",
            "0018_remove_payslip_category_remove_payslip_payroll_items_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payslipitem",
            name="payslip",
        ),
        migrations.RemoveField(
            model_name="payslipitem",
            name="payroll_item",
        ),
        migrations.DeleteModel(
            name="PaySlip",
        ),
        migrations.DeleteModel(
            name="PaySlipItem",
        ),
    ]
