# Generated by Django 5.0.1 on 2024-02-26 06:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0019_remove_payslipitem_payslip_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaySlip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=15)),
                ("category", models.CharField(max_length=128)),
                (
                    "date",
                    models.DateField(default=datetime.date.today, verbose_name="Date"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="button to toggle employee deleted and undelete",
                        verbose_name="Is This Employee Deleted ?",
                    ),
                ),
                (
                    "payroll_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payroll.payrollitem",
                    ),
                ),
                (
                    "salary",
                    models.ForeignKey(
                        limit_choices_to={"is_deleted": False},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payroll.salary",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payslip",
                "verbose_name_plural": "Payslips",
            },
        ),
    ]
