# Generated by Django 5.0.1 on 2024-02-26 07:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0020_payslip"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payslip",
            name="category",
        ),
        migrations.RemoveField(
            model_name="payslip",
            name="payroll_item",
        ),
        migrations.RemoveField(
            model_name="payslip",
            name="value",
        ),
    ]
