# Generated by Django 5.0.1 on 2024-02-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "payroll",
            "0021_remove_payslip_category_remove_payslip_payroll_item_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="payslip",
            name="payroll_items",
            field=models.ManyToManyField(to="payroll.payrollitem"),
        ),
    ]
