# Generated by Django 5.0.1 on 2024-02-26 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0022_payslip_payroll_items"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(default=datetime.date.today, verbose_name="Date"),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="PaySlip",
        ),
    ]
