# Generated by Django 5.0.1 on 2024-02-27 12:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0033_alter_attendanceregister_status"),
        ("main", "0001_initial"),
        ("payroll", "0023_salarydata_delete_payslip"),
    ]

    operations = [
        migrations.AddField(
            model_name="salarydata",
            name="company",
            field=models.ForeignKey(
                default="64d741a8-4377-4a62-b443-c8175e525938",
                limit_choices_to={"is_deleted": False},
                on_delete=django.db.models.deletion.CASCADE,
                to="main.company",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="salarydata",
            name="employee",
            field=models.ForeignKey(
                default="11ec49bd-453f-4f25-99e1-60d3f488e964",
                limit_choices_to={"is_deleted": False},
                on_delete=django.db.models.deletion.CASCADE,
                to="employee.employee",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="salarydata",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="button to toggle employee deleted and undelete",
                verbose_name="Is This Employee Deleted ?",
            ),
        ),
        migrations.AddField(
            model_name="salarydata",
            name="net_salary",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Net Salary",
            ),
        ),
    ]
