# Generated by Django 5.0.1 on 2024-03-02 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0036_alter_attendanceregister_status"),
        ("main", "0001_initial"),
        ("payroll", "0025_payslip"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salarydata",
            name="company",
        ),
        migrations.RemoveField(
            model_name="salarydata",
            name="employee",
        ),
        migrations.CreateModel(
            name="DynamicField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=255)),
                (
                    "field_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("category", models.CharField(max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        limit_choices_to={"is_deleted": False},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.company",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        limit_choices_to={"is_deleted": False},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee.employee",
                    ),
                ),
                (
                    "payslip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payroll.payslip",
                    ),
                ),
            ],
            options={
                "unique_together": {("payslip", "field_name")},
            },
        ),
        migrations.DeleteModel(
            name="Salary",
        ),
        migrations.DeleteModel(
            name="SalaryData",
        ),
    ]
