# Generated by Django 5.0.1 on 2024-03-03 00:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "payroll",
            "0026_remove_salarydata_company_remove_salarydata_employee_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dynamicfield",
            options={
                "ordering": ["employee"],
                "verbose_name": "DynamicField",
                "verbose_name_plural": "DynamicFields",
            },
        ),
        migrations.AlterUniqueTogether(
            name="dynamicfield",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="dynamicfield",
            name="field_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
