# Generated by Django 5.0.1 on 2024-03-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0027_alter_dynamicfield_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dynamicfield",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="button to toggle employee deleted and undelete",
                verbose_name="Is This Employee Deleted ?",
            ),
        ),
    ]
