# Generated by Django 5.0.1 on 2024-03-03 04:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0028_dynamicfield_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payslip",
            name="company",
        ),
        migrations.RemoveField(
            model_name="payslip",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="payslip",
            name="employee",
        ),
        migrations.RemoveField(
            model_name="payslip",
            name="updator",
        ),
        migrations.DeleteModel(
            name="DynamicField",
        ),
        migrations.DeleteModel(
            name="PaySlip",
        ),
    ]
