# Generated by Django 5.0.1 on 2024-03-04 05:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0031_payslip"),
    ]

    operations = [
        migrations.AddField(
            model_name="salary",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
