# Generated by Django 5.0.1 on 2024-03-04 05:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0032_salary_date"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PaySlip",
        ),
    ]
