# Generated by Django 5.0.14 on 2026-06-29 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employee", "0001_initial"),
        ("main", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attendanceregister",
            name="company",
            field=models.ForeignKey(
                limit_choices_to={"is_deleted": False},
                on_delete=django.db.models.deletion.CASCADE,
                to="main.company",
            ),
        ),
        migrations.AddField(
            model_name="attendanceregister",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creator_%(class)s_objects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attendanceregister",
            name="updator",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updator_%(class)s_objects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="company",
            field=models.ForeignKey(
                limit_choices_to={"is_deleted": False},
                on_delete=django.db.models.deletion.CASCADE,
                to="main.company",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creator_%(class)s_objects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="updator",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updator_%(class)s_objects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="designation",
            name="company",
            field=models.ForeignKey(
                limit_choices_to={"is_deleted": False},
                on_delete=django.db.models.deletion.CASCADE,
                to="main.company",
            ),
        ),
        migrations.AddField(
            model_name="designation",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creator_%(class)s_objects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="designation",
            name="department",
            field=models.ForeignKey(
                limit_choices_to={"is_deleted": False},
                on_delete=django.db.models.deletion.CASCADE,
                to="employee.department",
            ),
        ),
        migrations.AddField(
            model_name="designation",
            name="updator",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updator_%(class)s_objects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="company",
            field=models.ForeignKey(
                limit_choices_to={"is_deleted": False},
                on_delete=django.db.models.deletion.CASCADE,
                to="main.company",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creator_%(class)s_objects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                limit_choices_to={"is_deleted": False},
                on_delete=django.db.models.deletion.CASCADE,
                to="employee.department",
                verbose_name="Department",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="designation",
            field=models.ForeignKey(
                limit_choices_to={"is_deleted": False},
                on_delete=django.db.models.deletion.CASCADE,
                to="employee.designation",
                verbose_name="Role",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="updator",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updator_%(class)s_objects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="attendanceregister",
            name="employee",
            field=models.ForeignKey(
                limit_choices_to={"is_deleted": False},
                on_delete=django.db.models.deletion.CASCADE,
                to="employee.employee",
            ),
        ),
        migrations.AddField(
            model_name="holiday",
            name="company",
            field=models.ForeignKey(
                limit_choices_to={"is_deleted": False},
                on_delete=django.db.models.deletion.CASCADE,
                to="main.company",
            ),
        ),
        migrations.AddField(
            model_name="holiday",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creator_%(class)s_objects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="holiday",
            name="updator",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updator_%(class)s_objects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leave",
            name="company",
            field=models.ForeignKey(
                limit_choices_to={"is_deleted": False},
                on_delete=django.db.models.deletion.CASCADE,
                to="main.company",
            ),
        ),
        migrations.AddField(
            model_name="leave",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creator_%(class)s_objects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leave",
            name="employee",
            field=models.ForeignKey(
                limit_choices_to={"is_deleted": False},
                on_delete=django.db.models.deletion.CASCADE,
                to="employee.employee",
            ),
        ),
        migrations.AddField(
            model_name="leave",
            name="updator",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updator_%(class)s_objects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="company",
            field=models.ForeignKey(
                limit_choices_to={"is_deleted": False},
                on_delete=django.db.models.deletion.CASCADE,
                to="main.company",
            ),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creator_%(class)s_objects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="updator",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updator_%(class)s_objects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leave",
            name="leavetype",
            field=models.ForeignKey(
                limit_choices_to={"is_deleted": False},
                on_delete=django.db.models.deletion.CASCADE,
                to="employee.leavetype",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="employee",
            unique_together={("user", "company", "employeeid", "email")},
        ),
    ]
