# Generated by Django 5.0.14 on 2026-06-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendanceregister",
            name="status",
            field=models.CharField(
                choices=[
                    ("absent", "Absent"),
                    ("present", "Present"),
                    ("half-day", "Half"),
                ],
                default="absent",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Other", "Other"), ("Female", "Female"), ("Male", "Male")],
                max_length=125,
                null=True,
                verbose_name="Gender",
            ),
        ),
    ]
