# Generated by Django 4.2.1 on 2024-07-30 15:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("candidate", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateInterview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("auto_id", models.PositiveIntegerField(db_index=True, unique=True)),
                ("a_id", models.PositiveIntegerField()),
                ("date_added", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("date_updated", models.DateTimeField(auto_now_add=True)),
                ("date_time", models.DateTimeField()),
                ("additional_information", models.TextField(blank=True, null=True)),
                (
                    "interview_status",
                    models.CharField(
                        choices=[
                            ("Interview not done", "Interview not done"),
                            ("Sent an offer letter", "Sent an offer letter"),
                            ("Better luck next time", "Better luck next time"),
                            ("Waiting List", "Waiting List"),
                            ("Rejected", "Rejected"),
                        ],
                        max_length=255,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "CandidateInterview",
                "verbose_name_plural": "CandidateInterviews",
                "ordering": ["date_time"],
            },
        ),
        migrations.CreateModel(
            name="CandidateJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_title",
                    models.CharField(max_length=255, verbose_name="Job Title"),
                ),
                (
                    "job_location",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Job Location",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "salary_from",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Salary From"
                    ),
                ),
                (
                    "salary_to",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Salary To"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("No Offer", "No Offer"),
                            ("Offer a job", "Offer a job"),
                            ("Job Offered", "Job Offered"),
                            ("Assign Task", "Assign Task"),
                            ("Interested in the Job", "Interested in the Job"),
                            ("Interview Scheduled", "Interview Scheduled"),
                            ("Interview Done", "Interview Done"),
                            ("Cancelled/Rejected", "Cancelled/Rejected"),
                        ],
                        default="Offer a job",
                        max_length=255,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "CandidateJob",
                "verbose_name_plural": "CandidateJobs",
                "ordering": ["job_title"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("auto_id", models.PositiveIntegerField(db_index=True, unique=True)),
                ("a_id", models.PositiveIntegerField()),
                ("date_added", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("date_updated", models.DateTimeField(auto_now_add=True)),
                (
                    "job_title",
                    models.CharField(max_length=255, verbose_name="Job Title"),
                ),
                (
                    "job_location",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Job Location",
                    ),
                ),
                (
                    "no_of_vacancies",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Number Of Vacancies",
                    ),
                ),
                (
                    "experience",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Experience"
                    ),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Age"
                    ),
                ),
                (
                    "salary_from",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Salary From"
                    ),
                ),
                (
                    "salary_to",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Salary To"
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Full Time", "Full Time"),
                            ("Part Time", "Part time"),
                            ("Internship", "Internship"),
                            ("Contract", "Contract"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "job_category",
                    models.CharField(
                        choices=[
                            ("Full Stack Development", "Full Stack Development"),
                            ("Marketing", "Marketing"),
                            ("Accounting", "Accounting"),
                            ("Design Engineering", "Design Engineering"),
                            ("Matlab", "Matlab"),
                        ],
                        default="Full Stack Development",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Open", "Open"), ("Close", "Close")], max_length=255
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="start date",
                        null=True,
                        verbose_name="Start Date",
                    ),
                ),
                (
                    "expired_date",
                    models.DateField(
                        blank=True,
                        help_text="expired date",
                        null=True,
                        verbose_name="Expired Date",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
                "ordering": ["job_title"],
            },
        ),
        migrations.CreateModel(
            name="JobApplicant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("auto_id", models.PositiveIntegerField(db_index=True, unique=True)),
                ("a_id", models.PositiveIntegerField()),
                ("date_added", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("date_updated", models.DateTimeField(auto_now_add=True)),
                (
                    "hiring_status",
                    models.CharField(
                        choices=[
                            ("Not an applicant", "Not an applicant"),
                            ("Applicant", "Applicant"),
                            ("Hired", "Hired"),
                            ("Assign Task", "Assign Task"),
                            ("Interview Scheduled", "Interview Scheduled"),
                            ("Interview Done", "Interview Done"),
                            ("Cancelled/Rejected", "Cancelled/Rejected"),
                        ],
                        default="Not an Applicant",
                        max_length=255,
                    ),
                ),
                ("is_blocked", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "candidate",
                    models.ForeignKey(
                        limit_choices_to={"is_deleted": False},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="candidate.candidate",
                    ),
                ),
            ],
            options={
                "verbose_name": "JobApplicant",
                "verbose_name_plural": "JobApplicants",
                "ordering": ["job"],
            },
        ),
    ]
