# Generated by Django 5.0.1 on 2024-03-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0005_alter_job_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("Full Time", "Full Time"),
                    ("Part Time", "Part time"),
                    ("Internship", "Internship"),
                    ("Contract", "Contract"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[("Open", "Open"), ("Close", "Close")], max_length=255
            ),
        ),
    ]
