# Generated by Django 5.0.1 on 2024-04-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0006_alter_job_job_type_alter_job_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="job_category",
            field=models.CharField(
                choices=[
                    ("Full Stack Development", "Full Stack Development"),
                    ("Marketing", "Marketing"),
                    ("Accounting", "Accounting"),
                    ("Design Engineering", "Design Engineering"),
                    ("Matlab", "Matlab"),
                ],
                default="Full Stack Development",
                max_length=255,
            ),
        ),
    ]
