# Generated by Django 5.0.1 on 2024-04-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0008_candidatejob"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatejob",
            name="status",
            field=models.CharField(
                choices=[("No Offer", "No Offer"), ("Job Offered", "Job Offered")],
                default="No Offer",
                max_length=255,
            ),
        ),
    ]
