# Generated by Django 5.0.1 on 2024-04-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0009_candidatejob_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidatejob",
            name="status",
            field=models.CharField(
                choices=[
                    ("No Offer", "No Offer"),
                    ("Job Offered", "Job Offered"),
                    ("Assign Task", "Assign Task"),
                    ("Schedule Interview", "Schedule Interview"),
                ],
                default="No Offer",
                max_length=255,
            ),
        ),
    ]
