# Generated by Django 5.0.1 on 2024-04-22 09:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0009_alter_candidate_job_type_alter_candidate_status"),
        ("job", "0010_alter_candidatejob_status"),
        ("main", "0005_portfolio"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidatejob",
            name="status",
            field=models.CharField(
                choices=[
                    ("Offer a job", "Offer a job"),
                    ("Job Offered", "Job Offered"),
                    ("Assign Task", "Assign Task"),
                    ("Interested in the Job", "Interested in the Job"),
                    ("Interview Scheduled", "Interview Scheduled"),
                    ("Interview Done", "Interview Done"),
                    ("Cancelled/Rejected", "Cancelled/Rejected"),
                ],
                default="Offer a job",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Full Time", "Full Time"),
                    ("Part Time", "Part time"),
                    ("Internship", "Internship"),
                    ("Contract", "Contract"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="CandidateInterview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("auto_id", models.PositiveIntegerField(db_index=True, unique=True)),
                ("a_id", models.PositiveIntegerField()),
                ("date_added", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("date_updated", models.DateTimeField(auto_now_add=True)),
                ("date_time", models.DateTimeField()),
                ("additional_information", models.TextField(blank=True, null=True)),
                (
                    "interview_status",
                    models.CharField(
                        choices=[
                            ("Interview not done", "Interview not done"),
                            ("Sent an offer letter", "Sent an offer letter"),
                            ("Better luck next time", "Better luck next time"),
                            ("Waiting List", "Waiting List"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Interview not done",
                        max_length=255,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "candidate",
                    models.ForeignKey(
                        limit_choices_to={"is_deleted": False},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="candidate.candidate",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        limit_choices_to={"is_deleted": False},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.company",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator_%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updator",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updator_%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "CandidateInterview",
                "verbose_name_plural": "CandidateInterviews",
                "ordering": ["date_time"],
            },
        ),
    ]
