# Generated by Django 5.0.1 on 2024-04-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0011_alter_candidatejob_status_alter_job_job_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateinterview",
            name="interview_status",
            field=models.CharField(
                choices=[
                    ("Interview not done", "Interview not done"),
                    ("Sent an offer letter", "Sent an offer letter"),
                    ("Better luck next time", "Better luck next time"),
                    ("Waiting List", "Waiting List"),
                    ("Rejected", "Rejected"),
                ],
                max_length=255,
            ),
        ),
    ]
