# Generated by Django 5.0.1 on 2024-05-03 05:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0009_alter_candidate_job_type_alter_candidate_status"),
        ("job", "0012_alter_candidateinterview_interview_status"),
        ("main", "0005_portfolio"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobApplicant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("auto_id", models.PositiveIntegerField(db_index=True, unique=True)),
                ("a_id", models.PositiveIntegerField()),
                ("date_added", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("date_updated", models.DateTimeField(auto_now_add=True)),
                (
                    "hiring_status",
                    models.CharField(
                        choices=[
                            ("Not an applicant", "Not an applicant"),
                            ("Applicant", "Applicant"),
                            ("Hired", "Hired"),
                            ("Assign Task", "Assign Task"),
                            ("Interview Scheduled", "Interview Scheduled"),
                            ("Interview Done", "Interview Done"),
                            ("Cancelled/Rejected", "Cancelled/Rejected"),
                        ],
                        default="Not an Applicant",
                        max_length=255,
                    ),
                ),
                ("is_blocked", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "candidate",
                    models.ForeignKey(
                        limit_choices_to={"is_deleted": False},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="candidate.candidate",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        limit_choices_to={"is_deleted": False},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.company",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator_%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        limit_choices_to={"is_deleted": False},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="job.job",
                    ),
                ),
                (
                    "updator",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updator_%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "JobApplicant",
                "verbose_name_plural": "JobApplicants",
                "ordering": ["job"],
            },
        ),
    ]
