# Generated by Django 5.0.1 on 2024-05-23 05:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0014_alter_candidatejob_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CandidateJob",
        ),
    ]
