# Generated by Django 5.0.1 on 2024-05-23 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0010_alter_candidate_status"),
        ("job", "0015_delete_candidatejob"),
        ("main", "0006_emailsetting"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_title",
                    models.CharField(max_length=255, verbose_name="Job Title"),
                ),
                (
                    "job_location",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Job Location",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "salary_from",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Salary From"
                    ),
                ),
                (
                    "salary_to",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Salary To"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("No Offer", "No Offer"),
                            ("Offer a job", "Offer a job"),
                            ("Job Offered", "Job Offered"),
                            ("Assign Task", "Assign Task"),
                            ("Interested in the Job", "Interested in the Job"),
                            ("Interview Scheduled", "Interview Scheduled"),
                            ("Interview Done", "Interview Done"),
                            ("Cancelled/Rejected", "Cancelled/Rejected"),
                        ],
                        default="Offer a job",
                        max_length=255,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "candidate",
                    models.ForeignKey(
                        limit_choices_to={"is_deleted": False},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="candidate.candidate",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        limit_choices_to={"is_deleted": False},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "CandidateJob",
                "verbose_name_plural": "CandidateJobs",
                "ordering": ["job_title"],
            },
        ),
    ]
